import React, { useCallback, useEffect, useState } from 'react';
import { Download, History, Play, ShieldAlert, SlidersHorizontal, TableProperties, WandSparkles } from 'lucide-react';
import { Button } from '../../design-system/components/Button';
import { Card } from '../../design-system/components/Card';
import { Alert, EmptyState } from '../../design-system/components/Feedback';
import { apiCleanResearchDataset, apiGetDatasetAnalyses, apiGetDatasetIssues, apiGetDatasetVersions, apiGetResearchDataset, apiResolveDatasetIssue, apiRunResearchAnalysis, apiUpdateDatasetVariable, researchDatasetExportUrl } from '../../utils/api';

type Detail={id:string;name:string;current_version_id:string;dictionary:Array<{id:string;name:string;data_type:string;measurement_level:string;role:string;sensitive:boolean;identifier:boolean}>;preview:Array<Record<string,unknown>>;quality:{quality_score:number;missing_values:number;duplicates:number;outliers:number}};
type Issue={id:string;variable_name?:string;issue_type:string;severity:string;status:string;details:Record<string,unknown>};
type Version={id:string;version:string;kind:string;fingerprint:string;change_summary:string;created_at:string};
type Analysis={id:string;analysis_type:string;stale:boolean;result:Record<string,unknown>;engine_version:string};
export const DatasetWorkbench:React.FC<{datasetId:string;language:'ar'|'en';onChanged:()=>void}>=({datasetId,language,onChanged})=>{
 const ar=language==='ar'; const [tab,setTab]=useState('dictionary'); const [detail,setDetail]=useState<Detail|null>(null); const [issues,setIssues]=useState<Issue[]>([]); const [versions,setVersions]=useState<Version[]>([]); const [analyses,setAnalyses]=useState<Analysis[]>([]); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(''); const [noticeTone,setNoticeTone]=useState<'danger'|'warning'|'success'>('success');
 const showNotice=(tone:'danger'|'warning'|'success', message:string)=>{setNoticeTone(tone);setNotice(message);};
 const load=useCallback(async()=>{const [d,i,v,a]=await Promise.all([apiGetResearchDataset(datasetId),apiGetDatasetIssues(datasetId),apiGetDatasetVersions(datasetId),apiGetDatasetAnalyses(datasetId)]);setDetail(d);setIssues(i);setVersions(v);setAnalyses(a);},[datasetId]);
 useEffect(()=>{load().catch(()=>showNotice('danger', ar?'تعذر تحميل تفاصيل مجموعة البيانات':'Could not load dataset details'));},[load,ar]);
 const run=async()=>{if(!detail)return;const numeric=detail.dictionary.filter(v=>['INTEGER','FLOAT'].includes(v.data_type));if(!numeric[0]){showNotice('warning', ar?'لا يوجد متغير رقمي صالح للتحليل':'No numeric variable is available');return;}setBusy(true);try{await apiRunResearchAnalysis(datasetId,{dataset_version_id:detail.current_version_id,analysis_type:'DESCRIPTIVES',configuration:{variables:[numeric[0].name]}});await load();showNotice('success', ar?'اكتمل التحليل الوصفي وحُفظت اللقطة':'Descriptive analysis completed and snapshotted');}catch{showNotice('danger', ar?'تعذر تشغيل التحليل':'Could not run the analysis');}finally{setBusy(false)}};
 const clean=async()=>{if(!detail)return;const text=detail.dictionary.find(v=>['STRING','CATEGORY'].includes(v.data_type));if(!text){showNotice('warning', ar?'لا يوجد متغير نصي لتطبيق التنظيف':'No text variable is available for cleaning');return;}setBusy(true);try{await apiCleanResearchDataset(datasetId,{operation:'TRIM_TEXT',variable:text.name,parameters:{},change_summary:`Trim whitespace in ${text.name}`});await load();onChanged();showNotice('success', ar?'أُنشئ إصدار مشتق دون تغيير البيانات الخام':'A derived version was created; raw data is unchanged');}catch{showNotice('danger', ar?'تعذر تنظيف المجموعة':'Could not clean the dataset');}finally{setBusy(false)}};
 if(!detail)return notice?<Card><Alert variant="danger">{notice}</Alert></Card>:<Card><p role="status" className="m-0 text-sm font-bold text-[var(--ds-text-muted)] motion-safe:animate-pulse">{ar?'جارٍ تحميل مساحة العمل…':'Loading workbench…'}</p></Card>;
 const selectClass='rounded-lg border border-[var(--ds-border-subtle)] bg-[var(--ds-surface-primary)] px-2 py-1.5 text-xs text-[var(--ds-text-primary)] focus:outline-none focus:ring-2 focus:ring-[var(--ds-primary-soft)]';
 const tabs=[['dictionary',TableProperties,ar?'القاموس والمعاينة':'Dictionary & preview'],['quality',ShieldAlert,ar?'الجودة':'Quality'],['cleaning',WandSparkles,ar?'التنظيف':'Cleaning'],['analysis',SlidersHorizontal,ar?'التحليل':'Analysis'],['history',History,ar?'السجل':'History']];
 return <section aria-label={ar?'مساحة عمل مجموعة البيانات':'Dataset workbench'} className="space-y-4"><Card padding="sm"><div className="flex flex-wrap gap-2" role="tablist">{tabs.map(([id,Icon,label])=><button key={String(id)} role="tab" aria-selected={tab===id} onClick={()=>setTab(String(id))} className={`inline-flex min-h-11 items-center gap-2 rounded-lg px-3 text-sm font-bold ${tab===id?'border border-[var(--ds-primary)] bg-[var(--ds-primary-soft)] text-[var(--ds-text-primary)]':'border border-transparent bg-[var(--ds-surface-secondary)] text-[var(--ds-text-secondary)]'}`}><Icon size={16}/>{label as string}</button>)}<a className="ms-auto inline-flex min-h-11 items-center gap-2 rounded-lg border border-[var(--ds-border-default)] px-3 text-sm font-bold" href={researchDatasetExportUrl(datasetId)}><Download size={16}/>{ar?'CSV آمن':'Safe CSV'}</a></div></Card>
 {notice&&<Alert variant={noticeTone}>{notice}</Alert>}
 {tab==='dictionary'&&<Card><div className="mb-4 flex items-center justify-between"><h3 className="m-0">{ar?'قاموس المتغيرات':'Variable dictionary'}</h3><b className="text-ink ds-numeric">{detail.quality.quality_score}%</b></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr>{(ar?['المتغير','النوع','مستوى القياس','الدور','حساس','معرّف']:['Variable','Type','Measurement','Role','Sensitive','Identifier']).map(x=><th className="p-3 text-start" key={x}>{x}</th>)}</tr></thead><tbody>{detail.dictionary.map(v=><tr className="border-t border-[var(--ds-border-subtle)]" key={v.id}><td className="p-3 font-bold">{v.name}</td><td>{v.data_type}</td><td><select className={selectClass} aria-label={`${v.name} measurement`} value={v.measurement_level} onChange={async e=>{await apiUpdateDatasetVariable(datasetId,v.id,{measurement_level:e.target.value});await load()}}><option>NOMINAL</option><option>ORDINAL</option><option>INTERVAL</option><option>RATIO</option><option>BINARY</option><option>COUNT</option><option>DATE_TIME</option><option>FREE_TEXT</option></select></td><td><select className={selectClass} aria-label={`${v.name} role`} value={v.role} onChange={async e=>{await apiUpdateDatasetVariable(datasetId,v.id,{role:e.target.value});await load()}}><option>OTHER</option><option>INDEPENDENT</option><option>DEPENDENT</option><option>GROUPING</option><option>COVARIATE</option><option>IDENTIFIER</option></select></td><td><input aria-label={`${v.name} sensitive`} type="checkbox" checked={v.sensitive} onChange={async e=>{await apiUpdateDatasetVariable(datasetId,v.id,{sensitive:e.target.checked});await load()}} className="h-4 w-4 rounded border-[var(--ds-border-default)] text-[var(--ds-primary)] focus:ring-[var(--ds-primary)] cursor-pointer"/></td><td>{v.identifier?'✓':'—'}</td></tr>)}</tbody></table></div><h4>{ar?'معاينة آمنة (25 صفًا كحد أقصى)':'Safe preview (up to 25 rows)'}</h4><pre className="max-h-64 overflow-auto rounded-xl bg-[var(--ds-surface-secondary)] p-4 text-xs" tabIndex={0}>{JSON.stringify(detail.preview,null,2)}</pre></Card>}
 {tab==='quality'&&<Card><h3 className="mt-0">{ar?'مركز جودة البيانات':'Data quality center'}</h3><div className="mb-5 grid grid-cols-1 min-[375px]:grid-cols-3 gap-3 text-center"><div><b className={`ds-numeric ${detail.quality.missing_values>0?'text-warning':'text-ink'}`}>{detail.quality.missing_values}</b><small className="block">{ar?'مفقودة':'Missing'}</small></div><div><b className={`ds-numeric ${detail.quality.duplicates>0?'text-warning':'text-ink'}`}>{detail.quality.duplicates}</b><small className="block">{ar?'تكرارات':'Duplicates'}</small></div><div><b className={`ds-numeric ${detail.quality.outliers>0?'text-warning':'text-ink'}`}>{detail.quality.outliers}</b><small className="block">{ar?'متطرفة':'Outliers'}</small></div></div>{issues.length===0?<EmptyState bare className="py-4" title={ar?'لا توجد مشكلات مسجلة':'No recorded issues'} description={ar?'لم تُرصد مشكلات جودة على هذه المجموعة بعد.':'No quality issues have been recorded for this dataset yet.'}/>:<ul className="space-y-3 p-0">{issues.map(i=><li className="flex flex-wrap items-center gap-3 rounded-xl border border-[var(--ds-border-subtle)] p-3" key={i.id}><b>{i.issue_type}</b><span>{i.variable_name||'Dataset'}</span><span className={`text-xs font-bold ${i.severity==='HIGH'?'text-danger':i.severity==='MEDIUM'?'text-warning':'text-ink'}`}>{i.severity}</span><span className="text-xs text-[var(--ds-text-muted)]">{i.status}</span>{i.status==='OPEN'&&<Button size="sm" variant="outline" onClick={async()=>{await apiResolveDatasetIssue(datasetId,i.id,{status:'REVIEWED',resolution:'Reviewed by researcher in quality center'});await load();onChanged()}}>{ar?'تأكيد المراجعة':'Mark reviewed'}</Button>}</li>)}</ul>}</Card>}
 {tab==='cleaning'&&<Card><h3 className="mt-0">{ar?'تنظيف غير إتلافي':'Non-destructive cleaning'}</h3><p>{ar?'سيُطبّق Trim على أول متغير نصي ويُنشئ إصدارًا مشتقًا موثقًا. لا تتغير النسخة الخام.':'Trims the first text variable into a documented derived version. The raw version is never changed.'}</p><Button loading={busy} iconBefore={<WandSparkles size={16}/>} onClick={clean}>{ar?'إنشاء إصدار منظّف':'Create cleaned version'}</Button></Card>}
 {tab==='analysis'&&<Card><h3 className="mt-0">{ar?'التحليل الكمي الموثق':'Reproducible quantitative analysis'}</h3><p>{ar?'تشغيل الإحصاءات الوصفية لأول متغير رقمي مع حفظ الإعدادات وإصدار البيانات والمحرك.':'Run descriptives for the first numeric variable and snapshot the configuration, dataset version and engine.'}</p><Button loading={busy} iconBefore={<Play size={16}/>} onClick={run}>{ar?'تشغيل التحليل':'Run analysis'}</Button>{analyses.length===0?<EmptyState bare className="mt-5 py-4" title={ar?'لا توجد تحليلات محفوظة':'No saved analyses'} description={ar?'شغّل التحليل الوصفي لحفظ لقطة قابلة لإعادة الإنتاج.':'Run descriptives to snapshot a reproducible result.'}/>:<div className="mt-5 space-y-3">{analyses.map(a=><article key={a.id} className="rounded-xl border border-[var(--ds-border-subtle)] p-4"><div className="flex justify-between"><b>{a.analysis_type}</b>{a.stale&&<span className="text-[var(--ds-warning)]">{ar?'قديم — ليس خطأ':'Stale — not an error'}</span>}</div><small>{a.engine_version}</small><pre className="mt-3 overflow-auto text-xs ds-numeric" dir="ltr" tabIndex={0}>{JSON.stringify(a.result,null,2)}</pre></article>)}</div>}</Card>}
 {tab==='history'&&<Card><h3 className="mt-0">{ar?'سجل الإصدارات وقابلية إعادة الإنتاج':'Versions & reproducibility'}</h3>{versions.length===0?<EmptyState bare className="py-4" title={ar?'لا توجد إصدارات بعد':'No versions yet'} description={ar?'ستظهر هنا إصدارات البيانات بعد التحميل أو التنظيف.':'Dataset versions appear here after upload or cleaning.'}/>:<ol className="space-y-3">{versions.map(v=><li key={v.id}><b>v{v.version} · {v.kind}</b><p className="my-1 text-sm">{v.change_summary}</p><code className="break-all text-xs">SHA-256 {v.fingerprint}</code></li>)}</ol>}</Card>}
 </section>
}
