export const typography = {
  fontFamilies: {
    arabic: "'IBM Plex Sans Arabic', system-ui, sans-serif",
    latin: "Inter, system-ui, sans-serif",
    sans: "'IBM Plex Sans Arabic', Inter, system-ui, sans-serif",
    academic: "'IBM Plex Sans Arabic', Inter, system-ui, sans-serif",
    mono: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  },
  weights: {
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },
  sizes: {
    'display-xl': { fontSize: '2.5rem', lineHeight: '3.25rem', fontWeight: '700' },
    'display-lg': { fontSize: '2rem', lineHeight: '2.5rem', fontWeight: '700' },
    'heading-1': { fontSize: '1.75rem', lineHeight: '2.25rem', fontWeight: '700' },
    'heading-2': { fontSize: '1.5rem', lineHeight: '2rem', fontWeight: '600' },
    'heading-3': { fontSize: '1.25rem', lineHeight: '1.75rem', fontWeight: '600' },
    'heading-4': { fontSize: '1.125rem', lineHeight: '1.5rem', fontWeight: '600' },
    'body-lg': { fontSize: '1.0625rem', lineHeight: '1.7rem', fontWeight: '400' },
    'body': { fontSize: '0.9375rem', lineHeight: '1.6rem', fontWeight: '400' },
    'body-sm': { fontSize: '0.875rem', lineHeight: '1.45rem', fontWeight: '400' },
    'label': { fontSize: '0.8125rem', lineHeight: '1.125rem', fontWeight: '600' },
    'caption': { fontSize: '0.75rem', lineHeight: '1rem', fontWeight: '500' },
    'overline': { fontSize: '0.6875rem', lineHeight: '1rem', fontWeight: '600' },
    'metric': { fontSize: '1.875rem', lineHeight: '2.25rem', fontWeight: '700' },
    'code': { fontSize: '0.8125rem', lineHeight: '1.25rem', fontFamily: 'mono' },
  },
};
