import io
import hashlib
import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml

from ..models import CanonicalReportContext


def set_cell_background(cell, fill_hex: str):
    """Sets cell background color in docx."""
    shading_elm = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{fill_hex}"/>')
    cell._tc.get_or_add_tcPr().append(shading_elm)


def set_rtl(p):
    """Applies RTL direction to a python-docx paragraph."""
    pPr = p._p.get_or_add_pPr()
    pBdr = parse_xml(f'<w:bidi {nsdecls("w")}/>')
    pPr.append(pBdr)
    p.alignment = WD_ALIGN_PARAGRAPH.RIGHT


class DocxReportRenderer:
    @staticmethod
    def render(context: CanonicalReportContext, language: str = "ar") -> tuple[bytes, str]:
        """
        Renders CanonicalReportContext into a styled Word (.docx) document.
        Returns: (docx_bytes, document_hash)
        """
        doc = docx.Document()
        is_rtl = (language != "en")

        # Page Setup (Margins)
        for section in doc.sections:
            section.top_margin = Inches(1.0)
            section.bottom_margin = Inches(1.0)
            section.left_margin = Inches(1.0)
            section.right_margin = Inches(1.0)

            # Header
            header = section.header
            hp = header.paragraphs[0]
            hp.text = f"{context.manifest.organization_name_ar if is_rtl else context.manifest.organization_name_en} | {context.title_ar if is_rtl else context.title_en}"
            hp.alignment = WD_ALIGN_PARAGRAPH.RIGHT if is_rtl else WD_ALIGN_PARAGRAPH.LEFT
            hp.style.font.size = Pt(8.5)
            hp.style.font.color.rgb = RGBColor(120, 120, 120)

            # Footer
            footer = section.footer
            fp = footer.paragraphs[0]
            fp.text = f"منصة بصيرة للبحث العلمي — Baseerah Academic Suite | كود التحقق: {context.manifest.verification_code}"
            fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
            fp.style.font.size = Pt(8.0)
            fp.style.font.color.rgb = RGBColor(140, 140, 140)

        # ── Document Header / Title Page ──────────────────────────────────────
        org_p = doc.add_paragraph()
        if is_rtl:
            set_rtl(org_p)
        org_run = org_p.add_run(context.manifest.organization_name_ar if is_rtl else context.manifest.organization_name_en)
        org_run.font.size = Pt(13)
        org_run.font.bold = True
        org_run.font.color.rgb = RGBColor(79, 70, 229) # Indigo

        title_p = doc.add_paragraph()
        if is_rtl:
            set_rtl(title_p)
        title_run = title_p.add_run(context.title_ar if is_rtl else context.title_en)
        title_run.font.size = Pt(20)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(30, 27, 75)

        if context.subtitle_ar or context.subtitle_en:
            sub_p = doc.add_paragraph()
            if is_rtl:
                set_rtl(sub_p)
            sub_run = sub_p.add_run(context.subtitle_ar if is_rtl else context.subtitle_en)
            sub_run.font.size = Pt(11)
            sub_run.font.italic = True
            sub_run.font.color.rgb = RGBColor(100, 116, 139)

        doc.add_paragraph() # Spacer

        # ── Metadata Box ──────────────────────────────────────────────────────
        meta_table = doc.add_table(rows=2, cols=2)
        meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        meta_table.autofit = False

        cells = meta_table.rows[0].cells
        set_cell_background(cells[0], "F1F5F9")
        set_cell_background(cells[1], "F1F5F9")
        cells[0].text = f"معرف التقرير: {context.manifest.report_id}" if is_rtl else f"Report ID: {context.manifest.report_id}"
        cells[1].text = f"تاريخ التوليد: {context.manifest.generated_at[:10]}" if is_rtl else f"Generated: {context.manifest.generated_at[:10]}"

        cells2 = meta_table.rows[1].cells
        set_cell_background(cells2[0], "F8FAFC")
        set_cell_background(cells2[1], "F8FAFC")
        cells2[0].text = f"المستفيد/المستخدم: {context.manifest.generated_by_username}" if is_rtl else f"Generated By: {context.manifest.generated_by_username}"
        cells2[1].text = f"الجمهور المستهدف: {context.manifest.audience.value}" if is_rtl else f"Audience: {context.manifest.audience.value}"

        doc.add_paragraph() # Spacer

        # ── Sections ──────────────────────────────────────────────────────────
        for sec in context.sections:
            h_p = doc.add_paragraph()
            if is_rtl:
                set_rtl(h_p)
            h_run = h_p.add_run(sec.title_ar if is_rtl else sec.title_en)
            h_run.font.size = Pt(14)
            h_run.font.bold = True
            h_run.font.color.rgb = RGBColor(49, 46, 129)

            # Paragraphs
            paragraphs = sec.paragraphs_ar if is_rtl else sec.paragraphs_en
            if not paragraphs and is_rtl:
                paragraphs = sec.paragraphs_en
            elif not paragraphs:
                paragraphs = sec.paragraphs_ar

            for p_text in paragraphs:
                p = doc.add_paragraph()
                if is_rtl:
                    set_rtl(p)
                p.paragraph_format.line_spacing = 1.25
                p.paragraph_format.space_after = Pt(4)
                r = p.add_run(p_text)
                r.font.size = Pt(10.5)
                r.font.color.rgb = RGBColor(30, 41, 59)

            # Callouts
            callouts = sec.callouts_ar if is_rtl else sec.callouts_en
            for c_text in callouts:
                cp = doc.add_paragraph()
                if is_rtl:
                    set_rtl(cp)
                cp.paragraph_format.left_indent = Inches(0.25)
                cp.paragraph_format.right_indent = Inches(0.25)
                c_run = cp.add_run(f"📌 {c_text}")
                c_run.font.size = Pt(10)
                c_run.font.italic = True
                c_run.font.color.rgb = RGBColor(14, 116, 144)

            # Tables
            for tbl in sec.tables:
                headers = tbl.headers_ar if is_rtl else tbl.headers_en
                if not headers:
                    headers = tbl.headers_en or tbl.headers_ar

                if tbl.title_ar or tbl.title_en:
                    tp = doc.add_paragraph()
                    if is_rtl:
                        set_rtl(tp)
                    tr = tp.add_run(tbl.title_ar if is_rtl else tbl.title_en)
                    tr.font.size = Pt(11)
                    tr.font.bold = True
                    tr.font.color.rgb = RGBColor(71, 85, 105)

                if headers and tbl.rows:
                    t = doc.add_table(rows=len(tbl.rows) + 1, cols=len(headers))
                    t.alignment = WD_TABLE_ALIGNMENT.CENTER

                    # Header Row
                    for idx, h_col in enumerate(headers):
                        c = t.rows[0].cells[idx]
                        set_cell_background(c, "1E1B4B") # Navy
                        cp = c.paragraphs[0]
                        if is_rtl:
                            set_rtl(cp)
                        else:
                            cp.alignment = WD_ALIGN_PARAGRAPH.LEFT
                        cr = cp.add_run(str(h_col))
                        cr.font.bold = True
                        cr.font.size = Pt(9.5)
                        cr.font.color.rgb = RGBColor(255, 255, 255)

                    # Data Rows
                    for r_idx, row_data in enumerate(tbl.rows):
                        row_cells = t.rows[r_idx + 1].cells
                        bg = "F8FAFC" if r_idx % 2 == 0 else "FFFFFF"
                        for c_idx, val in enumerate(row_data):
                            if c_idx < len(row_cells):
                                cell = row_cells[c_idx]
                                set_cell_background(cell, bg)
                                cp = cell.paragraphs[0]
                                if is_rtl:
                                    set_rtl(cp)
                                else:
                                    cp.alignment = WD_ALIGN_PARAGRAPH.LEFT
                                vr = cp.add_run(str(val))
                                vr.font.size = Pt(9)
                                vr.font.color.rgb = RGBColor(30, 41, 59)

                doc.add_paragraph() # Spacer

        # ── Disclaimer ────────────────────────────────────────────────────────
        disclaimer = context.disclaimer_ar if is_rtl else context.disclaimer_en
        if disclaimer:
            dp = doc.add_paragraph()
            if is_rtl:
                set_rtl(dp)
            dp.paragraph_format.space_before = Pt(16)
            d_run = dp.add_run(f"⚠️ {disclaimer}")
            d_run.font.size = Pt(9)
            d_run.font.italic = True
            d_run.font.color.rgb = RGBColor(180, 83, 9)

        # ── Integrity & Verification Box ──────────────────────────────────────
        doc.add_paragraph()
        verif_p = doc.add_paragraph()
        if is_rtl:
            set_rtl(verif_p)
        verif_run = verif_p.add_run(
            f"رمز التحقق الأكاديمي الرقمي: {context.manifest.verification_code} | خوارزمية النزاهة: SHA-256"
            if is_rtl else
            f"Digital Academic Verification Code: {context.manifest.verification_code} | Integrity: SHA-256"
        )
        verif_run.font.size = Pt(8.5)
        verif_run.font.color.rgb = RGBColor(100, 116, 139)

        # Save to buffer
        buf = io.BytesIO()
        doc.save(buf)
        raw_bytes = buf.getvalue()
        doc_hash = hashlib.sha256(raw_bytes).hexdigest()
        return raw_bytes, doc_hash
