export interface ResearchPath {
  id: string;
  titleAr: string;
  titleEn: string;
  descriptionAr: string;
  descriptionEn: string;
  iconName: string;
  illustrationName: string;
  recommendedStageAr: string;
  recommendedStageEn: string;
  orderedSteps: string[]; // List of tool IDs
  primaryTools: string[];
  supportingTools: string[];
  requiredInputs: string[];
  expectedOutputs: string[];
  predictionCapabilities: string[];
  available: boolean;
  beta: boolean;
  category: 'design' | 'simulation' | 'fieldwork' | 'publishing';
}

export const RESEARCH_PATHS_CONFIG: ResearchPath[] = [
  {
    id: 'NEW_STUDY_DESIGN',
    titleAr: 'تصميم دراسة جديدة',
    titleEn: 'New Study Design',
    descriptionAr: 'تصميم وبناء المنهج الإحصائي والمتغيرات للدراسات التدخلية وشبه التجريبية خطوة بخطوة.',
    descriptionEn: 'Design and build the statistical methodology and variables for experimental studies.',
    iconName: 'FolderGit2',
    illustrationName: 'StudyDesignIllustration',
    recommendedStageAr: 'مرحلة التخطيط المبدئي',
    recommendedStageEn: 'Initial Planning Stage',
    orderedSteps: [
      'ideaExploration',
      'titleAnalysis',
      'problemGap',
      'objectives',
      'questionsHypotheses',
      'variables',
      'conceptualModel',
      'methodologyDesign',
      'populationSample',
      'measurementInstruments',
      'analysisPlan',
      'literatureEvidence',
      'simulation',
      'prediction',
      'consistencyValidation',
      'ethicsFeasibility',
      'preRegistration',
      'finalResearchPlan'
    ],
    primaryTools: ['wizard', 'analyzer', 'modelBuilder'],
    supportingTools: ['sampleCalc', 'consistency'],
    requiredInputs: ['titleAr'],
    expectedOutputs: ['projectId', 'variables', 'hypotheses', 'sampleSettings', 'preRegistrationHash'],
    predictionCapabilities: ['expectedEffectSize', 'minimumSample', 'methodologicalRisk'],
    available: true,
    beta: false,
    category: 'design'
  },
  {
    id: 'SEMINAR_PROPOSAL_REVIEW',
    titleAr: 'مراجعة خطة السمينار والأطروحة',
    titleEn: 'Seminar & Proposal Review',
    descriptionAr: 'تدقيق خطة البحث لغوياً ومنهجياً وعلمياً والتأكد من ملاءمة المتغيرات للفروض وصيغة العنوان.',
    descriptionEn: 'Audit study design, verify hypothesis alignment, and check linguistic consistency.',
    iconName: 'UserCheck',
    illustrationName: 'SeminarReviewIllustration',
    recommendedStageAr: 'مرحلة إقرار الخطة البحثية',
    recommendedStageEn: 'Proposal Approval Stage',
    orderedSteps: ['analyzer', 'consistency', 'modelBuilder', 'preReg'],
    primaryTools: ['analyzer', 'consistency'],
    supportingTools: ['modelBuilder'],
    requiredInputs: ['titleAr', 'variables', 'hypotheses'],
    expectedOutputs: ['consistencyScore', 'preRegistrationLockedAt'],
    predictionCapabilities: ['methodologicalRisk', 'deskRejectionRisks'],
    available: true,
    beta: false,
    category: 'design'
  },
  {
    id: 'FUTURE_OUTCOME_FORECAST',
    titleAr: 'التنبؤ المتقدم بالنتائج والمحاكاة',
    titleEn: 'Future Outcome Forecast & Simulation',
    descriptionAr: 'محاكاة مونت كارلو لدرجات الطلاب الافتراضية والتنبؤ باحتمال دعم الفرض قبل بدء القياس الميداني.',
    descriptionEn: 'Monte Carlo mock scores and Bayesian outcome forecast prior to field execution.',
    iconName: 'Brain',
    illustrationName: 'SimulationIllustration',
    recommendedStageAr: 'مرحلة قبل التطبيق الميداني',
    recommendedStageEn: 'Pre-implementation Stage',
    orderedSteps: ['sampleCalc', 'simulation', 'litSynthesizer', 'outcomePredictor'],
    primaryTools: ['simulation', 'outcomePredictor'],
    supportingTools: ['sampleCalc', 'litSynthesizer'],
    requiredInputs: ['sampleSettings', 'variables'],
    expectedOutputs: ['simulatedScenarios', 'predictedOutcome', 'predictionIntervals'],
    predictionCapabilities: ['expectedEffectSize', 'statisticalPower', 'probabilityOfSignificance'],
    available: true,
    beta: false,
    category: 'simulation'
  },
  {
    id: 'ACTIVE_FIELD_STUDY',
    titleAr: 'متابعة التنفيذ والدراسة الميدانية',
    titleEn: 'Active Field Study & Monitoring',
    descriptionAr: 'متابعة التزام المعلمين بالبروتوكول ونسب تسرب الطلاب وتعديل التنبؤات الإحصائية تلقائياً.',
    descriptionEn: 'Track teacher protocol compliance, attrition rates, and auto-update predictions.',
    iconName: 'Activity',
    illustrationName: 'FieldStudyIllustration',
    recommendedStageAr: 'مرحلة التطبيق الميداني والقياس',
    recommendedStageEn: 'Field Implementation Stage',
    orderedSteps: ['fidelity', 'outcomePredictor'],
    primaryTools: ['fidelity'],
    supportingTools: ['outcomePredictor'],
    requiredInputs: ['sampleSettings', 'projectId'],
    expectedOutputs: ['actualRecruitment', 'currentAttrition', 'fidelity'],
    predictionCapabilities: ['attritionForecast', 'completionForecast', 'fidelityForecast', 'statisticalPowerForecast'],
    available: true,
    beta: false,
    category: 'fieldwork'
  },
  {
    id: 'COMPLETED_STUDY_ANALYSIS',
    titleAr: 'تحليل الدراسة المكتملة والمقارنة',
    titleEn: 'Completed Study Analysis & Evaluation',
    descriptionAr: 'فحص جودة ملفات البيانات (Excel/CSV) ومقارنة النتائج الحقيقية الملحوظة بما كان متوقعاً.',
    descriptionEn: 'Inspect raw datasets for anomalies and match observed results with predictions.',
    iconName: 'Database',
    illustrationName: 'DataAnalysisIllustration',
    recommendedStageAr: 'مرحلة معالجة البيانات والتحليل',
    recommendedStageEn: 'Data Analysis Stage',
    orderedSteps: ['dataQuality', 'outcomePredictor'],
    primaryTools: ['dataQuality'],
    supportingTools: ['outcomePredictor'],
    requiredInputs: ['projectId'],
    expectedOutputs: ['dataQualityScore', 'observedEffectComparison'],
    predictionCapabilities: ['predictionVsObservedEvaluation'],
    available: true,
    beta: false,
    category: 'fieldwork'
  },
  {
    id: 'THESIS_DEFENSE_PREPARATION',
    titleAr: 'الاستعداد لمناقشة الرسالة العلميّة',
    titleEn: 'Thesis Defense Preparation',
    descriptionAr: 'مراجعة المبررات المنهجية وتحليل الانحرافات وحجج التفاوت بين المتوقع والملحوظ للمناقشين.',
    descriptionEn: 'Verify methodological rationales and prepare responses for defense review.',
    iconName: 'UserCheck',
    illustrationName: 'ThesisDefenceIllustration',
    recommendedStageAr: 'مرحلة ما قبل مناقشة الرسالة',
    recommendedStageEn: 'Pre-defense Stage',
    orderedSteps: ['outcomePredictor', 'reviewSim', 'export'],
    primaryTools: ['outcomePredictor'],
    supportingTools: ['reviewSim', 'export'],
    requiredInputs: ['projectId'],
    expectedOutputs: ['methodologicalRisk'],
    predictionCapabilities: ['methodologicalRiskForecast'],
    available: true,
    beta: false,
    category: 'publishing'
  },
  {
    id: 'SCIENTIFIC_PAPER_READING',
    titleAr: 'قراءة وتحليل ورقة بحثية مستقلة',
    titleEn: 'Scientific Paper Reading & Extraction',
    descriptionAr: 'تفكيك ورقة بحثية أجنبية واستخلاص المتغيرات وحجم الأثر لتسجيله في قاعدة المعرفة التاريخية.',
    descriptionEn: 'Deconstruct external studies, extract metrics, and update reference registry.',
    iconName: 'BookOpen',
    illustrationName: 'ReadingPaperIllustration',
    recommendedStageAr: 'مرحلة المسح المنهجي للأدبيات',
    recommendedStageEn: 'Literature Survey Stage',
    orderedSteps: ['analyzer', 'litSynthesizer'],
    primaryTools: ['litSynthesizer'],
    supportingTools: ['analyzer'],
    requiredInputs: [],
    expectedOutputs: ['literaturePrior'],
    predictionCapabilities: [],
    available: true,
    beta: true,
    category: 'design'
  },
  {
    id: 'MANUSCRIPT_PUBLICATION',
    titleAr: 'تجهيز المخطوطة للنشر العلمي والمراجعة',
    titleEn: 'Manuscript & Publication Readiness',
    descriptionAr: 'محاكاة كاملة لقرارات المحكمين بالمجلات وتخمين احتمالية الرفض المكتبي ونواقص الصياغة.',
    descriptionEn: 'Simulate peer reviewer evaluations and evaluate desk rejection risks.',
    iconName: 'UserCheck',
    illustrationName: 'ScientificPublishingIllustration',
    recommendedStageAr: 'مرحلة النشر والتقديم للمجلات',
    recommendedStageEn: 'Manuscript Submission Stage',
    orderedSteps: ['reviewSim', 'outcomePredictor'],
    primaryTools: ['reviewSim'],
    supportingTools: ['outcomePredictor'],
    requiredInputs: ['variables', 'hypotheses'],
    expectedOutputs: ['publicationReadiness', 'deskRejectionRisks'],
    predictionCapabilities: ['publicationReadinessForecast'],
    available: true,
    beta: false,
    category: 'publishing'
  },
  {
    id: 'SYSTEMATIC_REVIEW',
    titleAr: 'المراجعة المنهجية والتحليل التلوي',
    titleEn: 'Systematic Review & Meta-Analysis',
    descriptionAr: 'بناء مخطط تدفق PRISMA وإجراء حسابات الأثر التجميعي للدراسات السابقة إحصائياً.',
    descriptionEn: 'Build PRISMA flowcharts and calculate pooled random-effects parameters.',
    iconName: 'BookOpen',
    illustrationName: 'SystematicReviewIllustration',
    recommendedStageAr: 'مرحلة البحث النظري التأسيسي',
    recommendedStageEn: 'Foundational Review Stage',
    orderedSteps: ['prisma', 'litSynthesizer'],
    primaryTools: ['prisma', 'litSynthesizer'],
    supportingTools: [],
    requiredInputs: [],
    expectedOutputs: ['prismaFlowchart', 'pooledEffect'],
    predictionCapabilities: ['expectedEffectSize'],
    available: true,
    beta: false,
    category: 'design'
  },
  {
    id: 'QUALITATIVE_OR_MIXED_RESEARCH',
    titleAr: 'البحث النوعي والمنهج المختلط',
    titleEn: 'Qualitative & Mixed Research Lab',
    descriptionAr: 'تحليل المقابلات الميدانية وبناء الخرائط الموضوعية وربط التفسيرات بالدرجات الإحصائية الملحوظة.',
    descriptionEn: 'Analyze interviews, generate codes, and pair themes with quantitative metrics.',
    iconName: 'Sparkles',
    illustrationName: 'QualitativeResearchIllustration',
    recommendedStageAr: 'مرحلة التحليلات المتكاملة',
    recommendedStageEn: 'Mixed Methods Analysis Stage',
    orderedSteps: ['qualitative', 'dataQuality'],
    primaryTools: ['qualitative'],
    supportingTools: ['dataQuality'],
    requiredInputs: [],
    expectedOutputs: ['qualitativeCodes', 'thematicMap'],
    predictionCapabilities: [],
    available: true,
    beta: true,
    category: 'fieldwork'
  }
];
