"""add_workflow_paths_and_recommendations

Revision ID: 7fcf9334d0a5
Revises: 83a9e9b0faa2
Create Date: 2026-07-18 15:44:43.414683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcf9334d0a5'
down_revision: Union[str, Sequence[str], None] = '83a9e9b0faa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('runId', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('expectedImpact', sa.String(), nullable=True),
    sa.Column('effort', sa.String(), nullable=True),
    sa.Column('affectedMetric', sa.String(), nullable=True),
    sa.Column('evidenceSource', sa.String(), nullable=True),
    sa.Column('uncertainty', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['runId'], ['prediction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_recommendations_id'), ['id'], unique=False)

    with op.batch_alter_table('research_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activePathId', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('completedSteps', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('intelligenceProfile', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_projects', schema=None) as batch_op:
        batch_op.drop_column('intelligenceProfile')
        batch_op.drop_column('completedSteps')
        batch_op.drop_column('activePathId')

    with op.batch_alter_table('prediction_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_recommendations_id'))

    op.drop_table('prediction_recommendations')
    # ### end Alembic commands ###
