"""add_saas_multi_tenancy_tables

Revision ID: 8096fddda85f
Revises: 7fcf9334d0a5
Create Date: 2026-07-19 01:23:55.034623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8096fddda85f'
down_revision: Union[str, Sequence[str], None] = '7fcf9334d0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('organization_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('default_language', sa.String(), nullable=True),
    sa.Column('data_region', sa.String(), nullable=True),
    sa.Column('billing_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('suspended_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('billing_interval', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('limits_json', sa.JSON(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_plans_id'), ['id'], unique=False)

    op.create_table('organization_invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('accepted_at', sa.String(), nullable=True),
    sa.Column('revoked_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_invitations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_invitations_token_hash'), ['token_hash'], unique=True)

    op.create_table('organization_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=True),
    sa.Column('joined_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_memberships_id'), ['id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_customer_id', sa.String(), nullable=True),
    sa.Column('provider_subscription_id', sa.String(), nullable=True),
    sa.Column('current_period_start', sa.String(), nullable=False),
    sa.Column('current_period_end', sa.String(), nullable=False),
    sa.Column('trial_ends_at', sa.String(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('cancelled_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)

    op.create_table('usage_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.String(), nullable=False),
    sa.Column('billing_period', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_events_id'), ['id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('provider_invoice_id', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('amount_subtotal', sa.Float(), nullable=False),
    sa.Column('amount_tax', sa.Float(), nullable=False),
    sa.Column('amount_total', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('issued_at', sa.String(), nullable=False),
    sa.Column('due_at', sa.String(), nullable=True),
    sa.Column('paid_at', sa.String(), nullable=True),
    sa.Column('invoice_url', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('scan_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_storage_key'), ['storage_key'], unique=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizationId', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('before_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('after_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('request_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_audit_logs_organizations', 'organizations', ['organizationId'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('prediction_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizationId', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_prediction_runs_organizations', 'organizations', ['organizationId'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('project_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizationId', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_project_comments_organizations', 'organizations', ['organizationId'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('research_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizationId', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_research_projects_organizations', 'organizations', ['organizationId'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
    
    # ── SaaS Multi-Tenancy Data Backfill & Seeding ───────────────────────────
    import json
    import uuid
    import datetime
    
    now = datetime.datetime.utcnow().isoformat()
    connection = op.get_bind()
    
    # 1. Seed plans
    plans_to_seed = [
        {
            "id": "pln-free",
            "code": "PERSONAL_FREE",
            "name": "الباقة الشخصية المجانية",
            "description": "مشاريع شخصية أساسية مجانية للباحث الفردي",
            "billing_interval": "MONTHLY",
            "price": 0.0,
            "currency": "SAR",
            "is_active": True,
            "is_public": True,
            "trial_days": 0,
            "limits_json": json.dumps({
                "max_projects": 2,
                "max_members": 1,
                "max_storage_mb": 50,
                "ai_tokens_limit": 10000,
                "prediction_runs_limit": 5
            }),
            "features_json": json.dumps({
                "can_export": False,
                "reviewer_portal": False,
                "methodology_chat": True
            }),
            "created_at": now
        },
        {
            "id": "pln-pro",
            "code": "RESEARCHER_PRO",
            "name": "الباقة الاحترافية للباحث",
            "description": "مخططات متقدمة وتنبؤ شامل وحفظ التقارير كـ PDF",
            "billing_interval": "MONTHLY",
            "price": 149.0,
            "currency": "SAR",
            "is_active": True,
            "is_public": True,
            "trial_days": 14,
            "limits_json": json.dumps({
                "max_projects": 10,
                "max_members": 1,
                "max_storage_mb": 2000,
                "ai_tokens_limit": 100000,
                "prediction_runs_limit": 50
            }),
            "features_json": json.dumps({
                "can_export": True,
                "reviewer_portal": False,
                "methodology_chat": True
            }),
            "created_at": now
        },
        {
            "id": "pln-team",
            "code": "RESEARCH_TEAM",
            "name": "الباقة التعاونية للفرق",
            "description": "عمل جماعي مشترك وملاحظات مشرفين وبوابة التحكيم العلمي",
            "billing_interval": "MONTHLY",
            "price": 499.0,
            "currency": "SAR",
            "is_active": True,
            "is_public": True,
            "trial_days": 14,
            "limits_json": json.dumps({
                "max_projects": 25,
                "max_members": 10,
                "max_storage_mb": 10000,
                "ai_tokens_limit": 500000,
                "prediction_runs_limit": 200
            }),
            "features_json": json.dumps({
                "can_export": True,
                "reviewer_portal": True,
                "methodology_chat": True
            }),
            "created_at": now
        },
        {
            "id": "pln-inst",
            "code": "INSTITUTION",
            "name": "الباقة المؤسسية والجامعية",
            "description": "ربط مخصص للجامعات وإدارة مركزية مع دعم متكامل",
            "billing_interval": "MONTHLY",
            "price": 0.0,
            "currency": "SAR",
            "is_active": True,
            "is_public": True,
            "trial_days": 0,
            "limits_json": json.dumps({
                "max_projects": 9999,
                "max_members": 9999,
                "max_storage_mb": 500000,
                "ai_tokens_limit": 5000000,
                "prediction_runs_limit": 9999
            }),
            "features_json": json.dumps({
                "can_export": True,
                "reviewer_portal": True,
                "methodology_chat": True
            }),
            "created_at": now
        }
    ]
    
    # Insert plans safely (check existence first)
    for p in plans_to_seed:
        existing = connection.execute(sa.text("SELECT id FROM plans WHERE code = :code"), {"code": p["code"]}).fetchone()
        if not existing:
            connection.execute(
                sa.text(
                    "INSERT INTO plans (id, code, name, description, billing_interval, price, currency, is_active, is_public, trial_days, limits_json, features_json, created_at) "
                    "VALUES (:id, :code, :name, :description, :billing_interval, :price, :currency, :is_active, :is_public, :trial_days, :limits_json, :features_json, :created_at)"
                ),
                p
            )
            
    # 2. Backfill existing users (create Personal Workspaces)
    users = connection.execute(sa.text("SELECT id, username FROM users")).fetchall()
    
    for u in users:
        user_id = u[0]
        username = u[1]
        
        # Define personal organization details
        org_id = f"org-user-{user_id}"
        slug = f"personal-{username.lower()}"
        org_name = f"مساحة {username} الشخصية"
        
        # Check if organization already exists
        existing_org = connection.execute(sa.text("SELECT id FROM organizations WHERE id = :id"), {"id": org_id}).fetchone()
        if not existing_org:
            # Create organization
            connection.execute(
                sa.text(
                    "INSERT INTO organizations (id, name, slug, organization_type, status, owner_user_id, default_language, data_region, created_at) "
                    "VALUES (:id, :name, :slug, :organization_type, :status, :owner_user_id, :default_language, :data_region, :created_at)"
                ),
                {
                    "id": org_id,
                    "name": org_name,
                    "slug": slug,
                    "organization_type": "PERSONAL",
                    "status": "ACTIVE",
                    "owner_user_id": user_id,
                    "default_language": "ar",
                    "data_region": "sa",
                    "created_at": now
                }
            )
            
            # Create membership (OWNER role)
            connection.execute(
                sa.text(
                    "INSERT INTO organization_memberships (id, organization_id, user_id, role, status, created_at) "
                    "VALUES (:id, :organization_id, :user_id, :role, :status, :created_at)"
                ),
                {
                    "id": f"mbr-{str(uuid.uuid4())[:8]}",
                    "organization_id": org_id,
                    "user_id": user_id,
                    "role": "OWNER",
                    "status": "ACTIVE",
                    "created_at": now
                }
            )
            
            # Create default subscription to FREE plan
            connection.execute(
                sa.text(
                    "INSERT INTO subscriptions (id, organization_id, plan_id, status, provider, current_period_start, current_period_end, created_at) "
                    "VALUES (:id, :organization_id, :plan_id, :status, :provider, :current_period_start, :current_period_end, :created_at)"
                ),
                {
                    "id": f"sub-{str(uuid.uuid4())[:8]}",
                    "organization_id": org_id,
                    "plan_id": "pln-free",
                    "status": "ACTIVE",
                    "provider": "MOCK",
                    "current_period_start": now,
                    "current_period_end": (datetime.datetime.utcnow() + datetime.timedelta(days=3650)).isoformat(), # 10 years free
                    "created_at": now
                }
            )
            
            # 3. Associate all projects belonging to this user with this new Personal Organization
            connection.execute(
                sa.text("UPDATE research_projects SET organizationId = :org_id WHERE userId = :user_id"),
                {"org_id": org_id, "user_id": user_id}
            )
            
            # Associate comments, runs and audit logs
            projects = connection.execute(sa.text("SELECT id FROM research_projects WHERE organizationId = :org_id"), {"org_id": org_id}).fetchall()
            project_ids = [p[0] for p in projects]
            
            if project_ids:
                # Scoping SQL helper
                placeholders = ", ".join(f"'{pid}'" for pid in project_ids)
                connection.execute(
                    sa.text(f"UPDATE project_comments SET organizationId = :org_id WHERE projectId IN ({placeholders})"),
                    {"org_id": org_id}
                )
                connection.execute(
                    sa.text(f"UPDATE prediction_runs SET organizationId = :org_id WHERE projectId IN ({placeholders})"),
                    {"org_id": org_id}
                )
                
            connection.execute(
                sa.text("UPDATE audit_logs SET organizationId = :org_id WHERE userId = :user_id"),
                {"org_id": org_id, "user_id": user_id}
            )
            
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organizationId')

    with op.batch_alter_table('project_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organizationId')

    with op.batch_alter_table('prediction_runs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organizationId')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('request_id')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('after_json')
        batch_op.drop_column('before_json')
        batch_op.drop_column('organizationId')

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_storage_key'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_id'))

    op.drop_table('uploaded_files')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_events_id'))

    op.drop_table('usage_events')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_memberships_id'))

    op.drop_table('organization_memberships')
    with op.batch_alter_table('organization_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_invitations_token_hash'))
        batch_op.drop_index(batch_op.f('ix_organization_invitations_id'))

    op.drop_table('organization_invitations')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_id'))
        batch_op.drop_index(batch_op.f('ix_plans_code'))

    op.drop_table('plans')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
