"""add research data and analysis studio

Revision ID: d8e9f0a1b2c3
Revises: c5d6e7f8a0b1
"""
from alembic import op
import sqlalchemy as sa

revision = "d8e9f0a1b2c3"
down_revision = "c5d6e7f8a0b1"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("research_datasets", sa.Column("id",sa.String(),primary_key=True),sa.Column("organization_id",sa.String(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("project_id",sa.String(),sa.ForeignKey("research_projects.id",ondelete="CASCADE"),nullable=False),sa.Column("owner_id",sa.String(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(),nullable=False),sa.Column("source_type",sa.String(),nullable=False),sa.Column("sensitivity",sa.String(),nullable=False),sa.Column("status",sa.String(),nullable=False),sa.Column("current_version_id",sa.String()),sa.Column("created_at",sa.String(),nullable=False),sa.Column("updated_at",sa.String(),nullable=False))
    op.create_index("ix_dataset_org_project","research_datasets",["organization_id","project_id"])
    op.create_table("dataset_versions",sa.Column("id",sa.String(),primary_key=True),sa.Column("organization_id",sa.String(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("dataset_id",sa.String(),sa.ForeignKey("research_datasets.id",ondelete="CASCADE"),nullable=False),sa.Column("source_version_id",sa.String(),sa.ForeignKey("dataset_versions.id",ondelete="SET NULL")),sa.Column("uploaded_file_id",sa.String(),sa.ForeignKey("uploaded_files.id",ondelete="SET NULL")),sa.Column("version_number",sa.String(),nullable=False),sa.Column("kind",sa.String(),nullable=False),sa.Column("fingerprint",sa.String(),nullable=False),sa.Column("row_count",sa.Integer(),nullable=False),sa.Column("column_count",sa.Integer(),nullable=False),sa.Column("data_json",sa.JSON(),nullable=False),sa.Column("change_summary",sa.String()),sa.Column("created_by",sa.String(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_at",sa.String(),nullable=False),sa.UniqueConstraint("dataset_id","version_number",name="uq_dataset_version_number"))
    op.create_index("ix_dataset_version_org","dataset_versions",["organization_id","dataset_id"])
    op.create_table("dataset_variables",sa.Column("id",sa.String(),primary_key=True),sa.Column("organization_id",sa.String(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("dataset_id",sa.String(),sa.ForeignKey("research_datasets.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(),nullable=False),sa.Column("label_ar",sa.String()),sa.Column("label_en",sa.String()),sa.Column("description",sa.String()),sa.Column("data_type",sa.String(),nullable=False),sa.Column("measurement_level",sa.String(),nullable=False),sa.Column("role",sa.String(),nullable=False),sa.Column("allowed_values",sa.JSON()),sa.Column("missing_codes",sa.JSON()),sa.Column("sensitive",sa.Boolean(),nullable=False),sa.Column("identifier",sa.Boolean(),nullable=False),sa.UniqueConstraint("dataset_id","name",name="uq_dataset_variable_name"))
    op.create_table("dataset_quality_issues",sa.Column("id",sa.String(),primary_key=True),sa.Column("organization_id",sa.String(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("dataset_id",sa.String(),sa.ForeignKey("research_datasets.id",ondelete="CASCADE"),nullable=False),sa.Column("version_id",sa.String(),sa.ForeignKey("dataset_versions.id",ondelete="CASCADE"),nullable=False),sa.Column("variable_name",sa.String()),sa.Column("row_reference",sa.String()),sa.Column("issue_type",sa.String(),nullable=False),sa.Column("severity",sa.String(),nullable=False),sa.Column("status",sa.String(),nullable=False),sa.Column("details",sa.JSON()),sa.Column("resolution",sa.String()),sa.Column("created_at",sa.String(),nullable=False))
    op.create_table("research_analyses",sa.Column("id",sa.String(),primary_key=True),sa.Column("organization_id",sa.String(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("project_id",sa.String(),sa.ForeignKey("research_projects.id",ondelete="CASCADE"),nullable=False),sa.Column("dataset_id",sa.String(),sa.ForeignKey("research_datasets.id",ondelete="CASCADE"),nullable=False),sa.Column("dataset_version_id",sa.String(),sa.ForeignKey("dataset_versions.id",ondelete="RESTRICT"),nullable=False),sa.Column("research_question_id",sa.String(),sa.ForeignKey("research_questions.id",ondelete="SET NULL")),sa.Column("hypothesis_id",sa.String(),sa.ForeignKey("hypotheses.id",ondelete="SET NULL")),sa.Column("analysis_type",sa.String(),nullable=False),sa.Column("configuration",sa.JSON(),nullable=False),sa.Column("result",sa.JSON(),nullable=False),sa.Column("engine_version",sa.String(),nullable=False),sa.Column("status",sa.String(),nullable=False),sa.Column("created_by",sa.String(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_at",sa.String(),nullable=False))
    op.create_index("ix_analysis_org_project","research_analyses",["organization_id","project_id"])

def downgrade():
    op.drop_table("research_analyses"); op.drop_table("dataset_quality_issues"); op.drop_table("dataset_variables"); op.drop_table("dataset_versions"); op.drop_table("research_datasets")
